---
language: php

addons:
  apt:
    packages:
    - elinks # For dysplaying php files on console.
    - colordiff

cache:
  directories:
  - $HOME/.composer/cache/files

php:
- nightly
- 7.2
- 7.1
- 7.0

# env:
  # global:
  # - COMPOSER_BIN_DIR=bin
  # - COMPOSER=composer-dev.json # https://travis-ci.org/symfony-flex-demo/env-COMPOSER-and-symfony.lock
  # - PATH=$TRAVIS_BUILD_DIR/bin::$PATH

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

before_install:
- go get -u github.com/jingweno/ccat
- pip install --user pygments
# Disabling Xdebug - Debugger and Profiler Tool for PHP
- |
  php -r "print_r(get_loaded_extensions(TRUE));"
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    install --directory ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    php -r "print_r(get_loaded_extensions(TRUE));"
  fi
install:
- |
  composer create-project --no-install symfony/skeleton
  cd skeleton
  composer config bin-dir bin
  composer install
# - composer install # Needs to be after to allow the previous script to show downloads of new versions.
- composer global require sensiolabs/security-checker # At the end, not to interfer with showing downloads of new versions.

script:
- false # This .travis.yml has been copied from another repository and needs to be adapted!
# - composer require --no-scripts sensiolabs/security-checker &> /dev/null && composer exec --verbose security-checker security:check -- --end-point=http://security.sensiolabs.org/check_lock --ansi
- composer global exec --verbose                  -- security-checker security:check --end-point=http://security.sensiolabs.org/check_lock --ansi
# - composer global exec --verbose --working-dir=.. -- security-checker security:check --end-point=http://security.sensiolabs.org/check_lock --ansi
- composer exec --verbose -- console --ansi

after_script:
- ls --almost-all --color
- pygmentize -l sh -O linenos=1 .env
- pygmentize -l sh -O linenos=1 .env.dist
- ls --color bin
- php -s bin/console | elinks -force-html -dump-color-mode 4 -dump
- ls --almost-all --recursive --color var
- ls --color src
- ls --recursive --color config


- composer show --latest
- $GOPATH/bin/ccat composer.json
- $GOPATH/bin/ccat ../composer.json
# - diff --minimal --side-by-side --color composer-dev.json composer.json needs a Ubuntu version newer than Trusty
- colordiff --minimal --side-by-side composer.json ../composer.json

- composer exec --list
- composer run-script --list

- composer exec --verbose -- console list debug --ansi
- composer exec -vvv -- console --ansi
